export const MAIN_ROUTE = '/main'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const GOOGLE_REDIRECT_ROUTE = 'login/google/redirect'
export const SERVICE_MAP_ROUTE = '/service/map'
export const USER_MAP_ROUTE = '/main/map'
export const ADD_USER_CARS_ROUTE = '/main/add-user-cars'
export const MARKER_ZOOM = 13
export const MAP_ZOOM = 13
export const DIAGNOSTIC_OPERATION = 0;
export const CHAT_GPT_ROUTE = '/main/ai-help'
export const AWS_STATIC_FILES_ROUTE = '/service/aws-static-files-manager'
export const AWS_ADD_STATIC_FILE_ROUTE = '/service/aws-static-files-manager/add-static'
export const REPAIR_SIGNING = '/service/repair-signing'
export const CHAT_GPT_PATTERN = /(Inquiry|app|helper|authorised|car|service)/gi
export const STATIC_FILE_TYPES = ['part', 'guide']
